
#########################################        Properties           #########################################
spring :
    servlet :
        multipart :
            maxFileSize : 10MB      # 파일 하나의 최대 크기
            maxRequestSize : 30MB   # 한 번에 최대 업로드 가능 용량
    jpa :
        properties :
            hibernate :
                jdbc :
                    lob :
                        non_contextual_creation : 'true'
        hibernate :
            ddl-auto : none
    profiles :
        active : prod
        include : 
          - sns
    mvc :
        converters :
            preferred-json-mapper : gson

server :
    error :
        whitelabel :
            enabled : true
    servlet :
        session :
            persistent : true           # 재기동 해도 스프링 관련 세션 유지.
            timeout : 3600              # 세션 시간 (60분: 3600 )
    tomcat:
        connection-timeout: 15000 # 10000 = 10sec / 컨넥션 타임아웃 . 15초 이상 지연되면 타임아웃 exception 

# logging
logging:
  config: classpath:logback-spring.xml
  level:
      org.springframework.security: INFO
      org.hibernate.sql: INFO
      
error:
    log:
        config:
            filename: error
            
#p6spy query logging
decorator :
    datasource :
        p6spy :
            enable-logging : true
developer :
   motto : ==== Accept mistakes, doubt ease, avoid arrogance, and always consider Murphy’s Law. from jjeovi =====
   
key :
    default :
      admin : adm                                                     # 관리자 화면 기본 변수 key
      adminRootMenuSn : 100                                           # 관리자 루트 메뉴sn
      user  : pon                                                     # 사용자 화면 기본 변수 key
      userRootMenuSn  : 200                                           # 사용자 루트 메뉴sn
    admin : 
        auth : pon                                                    # 로그인 인증용 key (일반로그인 . SNS는 아님 XX )
    menuCd : 
        auth : mcd                                                    # 메뉴 코드 인증용 key
