spring :
    security:
      oauth2:
        client:
            registration:
#                   구글 SNS 로그인
                google: 
                    client-id: 373819329512-fm0php1b3jmtr7ohk3chf0kq43imscou.apps.googleusercontent.com
                    client-secret: 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
                    scope: profile,email
#                    카카오 SNS 로그인
                kakao:
                    client-id: 48d7c4d7ec6a3e72ecb901d80f7733ae
                    client-secret: whRaYzOU89oyW0yV7wq4sxmc6THlHrCK
                    scope: account_email
                    client-name: Kakao
                    authorization-grant-type: authorization_code
                    client-authentication-method: POST                                  # 카카오는 필수 파라미터를 POST로 요청해야됌!
                    redirect-uri: http://localhost:8880/login/oauth2/code/kakao         # 코드를 받는 uri( kakao 의 콜백 uri)
            provider:
                kakao:
                    authorization-uri : https://kauth.kakao.com/oauth/authorize
                    token-uri : https://kauth.kakao.com/oauth/token
                    user-info-uri : https://kapi.kakao.com/v2/user/me
                    user-name-attribute : id
