spring :
    servlet :
        multipart :
            maxFileSize : 10MB      # 파일 하나의 최대 크기
            maxRequestSize : 30MB   # 한 번에 최대 업로드 가능 용량
    devtools :
        livereload :
            enabled : true
        restart :
            enabled : true
    datasource :
        driver-class-name : org.postgresql.Driver
        url : jdbc:postgresql://db.jjeovi.gabia.io:5432/dbjjeovi
        username : jjeovi
        password : ponkids2023!
    jpa :
        properties :
            hibernate :
                jdbc :
                    lob :
                        non_contextual_creation : 'true'
                default_schema : ponkids_dev
        hibernate :
            ddl-auto : none
    thymeleaf :
        cache : false
    profiles :
        active : local
    mvc :
        converters :
            preferred-json-mapper : gson
    security:
      oauth2:
        client:
            registration:
                kakao:
                    client-id : xxx
                    client-secret : xxx
                    scope :
                        # - profile_nickname
                        - account_email
                    client-name : Kakao
                    authorization-grant-type : authorization_code
                    client-authentication-method : POST #카카오는 필수 파라미터를 POST로 요청해야됌!
                    redirect-uri : http://localhost:8880/login/oauth2/code/kakao #코드를 받는 uri(naver 의 콜백 uri)
            
            provider:
                kakao:
                    authorization-uri:
                    token-uri:
                    user-info-uri:
                    user-name-attribute:

server :
    error :
        whitelabel :
            enabled : true
    servlet :
        session :
            persistent : true          # 재기동 해도 스프링 관련 세션 유지.
            timeout : 3600              # 세션 시간 (60분: 3600 )

#p6spy query logging
decorator :
    datasource :
        p6spy :
            enable-logging : true

#########################################        System Variables           #########################################

key :
    default :
        admin : adm                                                     # 관리자 화면 기본 변수 key
        adminRootMenuSn : 100                                           # 관리자 루트 메뉴sn
        user  : pon                                                     # 사용자 화면 기본 변수 key
        userRootMenuSn  : 200                                           # 사용자 루트 메뉴sn
    upload :
#        path : C:/upload/                                              # 업로드 파일 저장 경로 ( 개발용 ) ( window )
        path : /Users/jjeoV/Desktop/jjeoV/2023/pioneerKids/upload/      # 업로드 파일 저장 경로 ( 개발용 ) ( Mac )
    menu:
 #       jsonFilePath : \file\menu\json\pon\                            # 사용자 메뉴 파일 생성 경로 ( window )
        jsonFilePath : /file/menu/json/pon/                             # 사용자 메뉴 파일 생성 경로 ( Mac )
    admin :
        auth : pon                  # 로그인 인증용 key
    menuCd :
        auth : mcd                  # 메뉴코드 인증용 key
        
upload :
    path : C:/upload/               # 업로드 파일 저장 경로 ( 개발용 ) ( window )
        
######################################################################################################################