################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################


#########################################        Properties           #############################################
spring :
    devtools :
        livereload :
            enabled : true
        restart : 
            enabled : true
    thymeleaf : 
        cache : false
    datasource :
        driver-class-name : org.postgresql.Driver
        url : jdbc:postgresql://db.jjeovi.gabia.io:5432/dbjjeovi
        username : jjeovi
        password : ponkids2023!
        hikari:
            maximumPoolSize : 2
            #idle-timeout: 1000
            #idleTimeout: 1000
            #max-lifetime : 2000
            #maxLifetime : 2000
            #keepalive-time : 1000
            #keepaliveTime : 1000
    jpa :
        properties :
            hibernate :
                default_schema : ponkids_dev
#                default_schema : ponkids


#########################################        sns-properties           #########################################
    security:
        oauth2:
            client:
                registration:
                    #                   구글 SNS 로그인
                    google:
                        client-id: 373819329512-fm0php1b3jmtr7ohk3chf0kq43imscou.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile,email
                    #                    카카오 SNS 로그인
                    kakao:
                        client-id: 48d7c4d7ec6a3e72ecb901d80f7733ae
                        client-secret: whRaYzOU89oyW0yV7wq4sxmc6THlHrCK
                        scope: account_email
                        client-name: kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST                                  # 카카오는 필수 파라미터를 POST로 요청해야됌!
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao         # 코드를 받는 uri( kakao 의 콜백 uri)
                        # 카카오 참고 url : https://kim-jong-hyun.tistory.com/150
                provider:
                    kakao:
                        authorization-uri : https://kauth.kakao.com/oauth/authorize
                        token-uri : https://kauth.kakao.com/oauth/token
                        user-info-uri : https://kapi.kakao.com/v2/user/me
                        user-name-attribute : id


#########################################        System Variables           #######################################

key :
    upload :
        path : /Users/jjeoV/Desktop/jjeoV/2023/pioneerKids/upload/      # 업로드 파일 저장 경로 ( 개발용 ) ( Mac )
    menu:
        jsonFilePath : /file/menu/json/pon/                             # 사용자 메뉴 파일 생성 경로 ( Mac )
    cmmnCd:
        jsonFilePath : /file/cmmnCd/                                   # 사용자 메뉴 파일 생성 경로 ( window )
    divider: /                                                          # 파일 구분자 ( window )
    summernote :
        upload :
            path : src/main/resources/summernote/uploads                # summernote 파일 업로드 경로 ( Mac )
    # 토스 결제 API
    tossPayments :
        baseUrl : https://api.tosspayments.com
        secretKey : test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
        
####################################################################################################################

#########################################        Email User Variables           #########################################

mail :
    smtp:
        host: smtp.gmail.com
        port: 587
        username: pioneerkids.us@gmail.com
        password: pbcsfudouqeaeopb

######################################################################################################################