##################################          real product  properties !!        ####################################
##################################          real product  properties !!        ####################################
##################################          real product  properties !!        ####################################
##################################          real product  properties !!        ####################################
##################################          real product  properties !!        ####################################


#########################################        Properties           #########################################
spring :
    thymeleaf : 
        cache : true
    datasource :
        driver-class-name : org.postgresql.Driver
        url : jdbc:postgresql://db.jjeovi.gabia.io:5432/dbjjeovi
        username : jjeovi
        password : ponkids2023!
    jpa :
        properties :
            hibernate :
                default_schema : ponkids
                
#########################################        sns-properties           #########################################                
    security:
      oauth2:
        client:
            registration:
#                   구글 SNS 로그인
                google: 
                    client-id: 859381259712-tur84mgvvd2s1i7bkf3a1c9ok5f9v412.apps.googleusercontent.com
                    client-secret: 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
                    scope: profile,email
#                    카카오 SNS 로그인
                kakao:
                    client-id: b0c2c83ed076dba404b439856be6385d
                    client-secret: aNC3LQes7ltoQG0yPHj2cPJhMKH3X5fk
                    scope: account_email
                    client-name: kakao
                    authorization-grant-type: authorization_code
                    client-authentication-method: client_secret_post                    # 카카오는 필수 파라미터를 POST로 요청해야됌!
                    redirect-uri: https://pioneerkids.us/login/oauth2/code/kakao        # 코드를 받는 uri( kakao 의 콜백 uri)
                    # 카카오 참고 url : https://kim-jong-hyun.tistory.com/150
            provider:
                kakao:
                    authorization-uri : https://kauth.kakao.com/oauth/authorize
                    token-uri : https://kauth.kakao.com/oauth/token
                    user-info-uri : https://kapi.kakao.com/v2/user/me
                    user-name-attribute : id
    profiles :
        inclue : oauth
                

#########################################        System Variables           #########################################

key :
    upload :
        path : /web/ponkids/upload/                                    # 업로드 파일 저장 경로  : 운영 서버
    menu :
        jsonFilePath : /file/menu/json/pon/                            # 사용자 메뉴 파일 생성 경로 : 운영 서버
    cmmnCd :
        jsonFilePath : /file/cmmnCd/
    divider : /
    summernote :
        upload :
            path : /web/ponkids/summernote/uploads/                    # summernote 파일 업로드 경로 : 운영 서버
    # 토스 결제 API
    tossPayments :
        baseUrl : https://api.tosspayments.com
        secretKey : test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
        
######################################################################################################################

#########################################        Email User Variables           #########################################

mail :
    smtp:
        host: smtp.gmail.com
        port: 587
        username: pioneerkids.us@gmail.com
        password: pbcsfudouqeaeopb

######################################################################################################################
