################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################
################################## (MAC OS) l o c a l  properties !!!! (MAC OS) ###################################


#########################################        Properties           #############################################
spring :
    devtools :
        livereload :
            enabled : true
        restart : 
            enabled : true
    thymeleaf : 
        cache : false
    datasource :
        driver-class-name : org.postgresql.Driver
        url : jdbc:postgresql://db.jjeovi.gabia.io:5432/dbjjeovi
        username : jjeovi
        password : ponkids2023!
        hikari:
            maximumPoolSize : 2
            #idle-timeout: 1000
            #idleTimeout: 1000
            #max-lifetime : 2000
            #maxLifetime : 2000
            #keepalive-time : 1000
            #keepaliveTime : 1000
    jpa :
        properties :
            hibernate :
                default_schema : ponkids_dev
#                default_schema : ponkids

#########################################        System Variables           #######################################

key :
    upload :
        path : /Users/jjeoV/Desktop/jjeoV/2023/pioneerKids/upload/      # 업로드 파일 저장 경로 ( 개발용 ) ( Mac )
    menu:
        jsonFilePath : /file/menu/json/pon/                             # 사용자 메뉴 파일 생성 경로 ( Mac )
    cmmnCd:
        jsonFilePath : /file/cmmnCd/                                   # 사용자 메뉴 파일 생성 경로 ( window )
    divider: /                                                          # 파일 구분자 ( window )
        
####################################################################################################################